### ISSUE TITLE
Problem with sudo ruby had-hide

### ISSUE THREAD

**Issue by geofgs** [jondkinney/UAD-Hide-And-Seek-Script#10]
Hello,

First, thanks for your work. I'm a noob on all of this and this seems to be the only solution to my problem. When I try to do things like you describe in terminal it shows this :

Last login: Fri Feb 26 15:29:34 on ttys000
macbook-pro-de-geoffrey:~ geoffreysella$ cd ~/Downloads/UAD-Hide-And-Seek-Script-master
macbook-pro-de-geoffrey:UAD-Hide-And-Seek-Script-master geoffreysella$ sudo ruby uad-hide
Password:
ruby: No such file or directory -- uad-hide (LoadError)
macbook-pro-de-geoffrey:UAD-Hide-And-Seek-Script-master geoffreysella$ 

Any idea of what could of gone wrong ?

Thanks a lot,

Have a good day

Geoffrey

**Comment by geofgs** [comment]
I'm so sorry for the previous message, but maybe some other people as noob as me will have the same. I should of thought I needed to write the full "sudo ruby uad-hide-and-seek.rb" 

Worked perfectly, saved tons of time organizing all the plugins !

I will support your work.

Have a great day

Geoffrey

**Comment by jondkinney** [comment]
Hey @geofgs! Thanks for the note. Sorry about the confusion. In the instructions I suggest typing that far and pressing `tab` to make sure that you don't accidentally type the file name wrong. But yea, that could be more clear. I'll take a look at the instructions in the coming weeks and try to clean that up. Thanks for the kind words! Glad the script helped you 👍 .
