### ISSUE TITLE
New UAD-Hide-And-Seek-Script for 9.15 version please

### ISSUE THREAD

**Issue by HaDRFakrrr** [jondkinney/UAD-Hide-And-Seek-Script#12]
do someone new version for New UAD-Hide-And-Seek-Script for 9.15 please? I tried to add new plugins, but the script didn't work. THX

**Comment by JUNOJACK** [comment]
Yes Please T.T
We want UHASS for 9.15 above 
Thank you so much!

**Comment by ViktorNacht** [comment]
So what happened is UAD changed the line endings in the UADSystemProfile.txt file from CRLF to Unix (just LF).

Look for:

.split("\r\n") # split the string into an array on each newline

And change it to:

.split("\n") # split the string into an array on each newline

Be careful to retain the whitespace before .split in the script or it will break. 

It would also be possible to change the matching to support both line endings, but I just did enough to make it work.

**Comment by ViktorNacht** [comment]
Another alternative is you can run unix2dos on the UADSystemProfile.txt file so you don't have to edit the script.

**Comment by HaDRFakrrr** [comment]
> So what happened is UAD changed the line endings in the UADSystemProfile.txt file from CRLF to Unix (just LF).
> 
> Look for:
> 
> .split("\r\n") # split the string into an array on each newline
> 
> And change it to:
> 
> .split("\n") # split the string into an array on each newline
> 
> Be careful to retain the whitespace before .split in the script or it will break.
> 
> It would also be possible to change the matching to support both line endings, but I just did enough to make it work.

THNX.... I will try both methods
