### ISSUE TITLE
Can't get this to work :-(

### ISSUE THREAD

**Issue by mrmox** [jondkinney/UAD-Hide-And-Seek-Script#13]
Hi, I would love to get this working but right now I just get an error on a missing file and when I correct the name in the script to point to the right plugin it will only move that plugin both on manual move or with the move all test. 

Im not super into scrips but I think Im doing it the right way.. 

Thanks!

OLe

**Comment by jondkinney** [comment]
@mrmox the script was quite outdated, but I've fixed it up now to account for all the nested folder changes. I also moved the case statement to a JSON file for easier maintenance. Please try it again and let me know if it's working better for you!

**Comment by mrmox** [comment]
Hi, Great that you revisited this! It worked with the UAD Console plugs but VST3 gave me this errror:

uad-hide-and-seek.rb:328:in `plug_case_statement': uninitialized constant PLUGIN_APPEND (NameError)
Did you mean?  PLUGIN_EXT
	from uad-hide-and-seek.rb:345:in `block in <main>'
	from uad-hide-and-seek.rb:344:in `each'
	from uad-hide-and-seek.rb:344:in `<main>'
Could this be because UAD now has a folder system with sorted plugs? Think its a new addition in the VST3 folder.
Cheers
